### ISSUE TITLE
Bugs/ test code for debugging included in snake_env.py

### ISSUE THREAD

**Issue by eunkich** [kc-ml2/marlenv#28]
https://github.com/kc-ml2/marlenv/blob/2ee67b739c63bca9b5810a01614448a196890424/marlenv/envs/snake_env.py#L520L522

@anthony0727 Seems accidently included to the commit. Was this intended?

**Comment by leeynsn** [comment]
removed it with the PR

**Comment by eunkich** [comment]
Thank you sir.
